### ISSUE TITLE
pixivrank获取图片问题。

### ISSUE THREAD

**Issue by 0769559** [shewinder/shebot_nb2#1]
一直用着2个月前的版本 用着不错 就是可惜最近频繁封号风控了。最近更新了一下后发现pixivrank推送方式变了。

个人提几个建议
1、目前好像只能1个指令一张图的获取 比较尴尬。
2、普通日榜好像不怕风控，真正需要的是r18，不知道能否普通日榜和r18日榜分别设置独立开关改回以前的推送方式
3、希望根目录里能有个单独的各个功能总开关的配置文件
4、希望pixivrank和setusearch功能能让私聊也用上
5、r18图片加个像素点二次处理或幻影坦克图 以达到反和谐（不知道是否难以实现 就当我口胡吧）

**Comment by 0769559** [comment]
pixivrank推送后如果重启了机器人，那么尝试获取原图就会提示日榜未更新

**Comment by shewinder** [comment]
1. 考虑过，但是怕群友贪多，卡死机器人。原来合并转发很好，可是最近都发不出来了，所以一直在探索新的方案
2. 推送模式开关可以有，有空加一下
3. 这个我也一直有想过，但是这个可以通过网页控制某个Service在所有群的开启禁用，就一直没加
4. 这个是因为之前一私聊就封号，把所有私聊全部移除了，可以考虑增加个总的私聊开关
5. 目前r18图是有反和谐处理的（修改像素点），但有时候还是发不出来
6. 我认为重启提示日榜未更新是能容忍的行为，但可以考虑加入持久化
PS：我根本没想过会有人用，所以改动很随意（

**Comment by 0769559** [comment]
> 1. 考虑过，但是怕群友贪多，卡死机器人。原来合并转发很好，可是最近都发不出来了，所以一直在探索新的方案
> 2. 推送模式开关可以有，有空加一下
> 3. 这个我也一直有想过，但是这个可以通过网页控制某个Service在所有群的开启禁用，就一直没加
> 4. 这个是因为之前一私聊就封号，把所有私聊全部移除了，可以考虑增加个总的私聊开关
> 5. 目前r18图是有反和谐处理的（修改像素点），但有时候还是发不出来
> 6. 我认为重启提示日榜未更新是能容忍的行为，但可以考虑加入持久化
>    PS：我根本没想过会有人用，所以改动很随意（

1、确实群里的人都频繁获取多张图的话 容易卡死机器人。给机器人加个cd之类的不知道如何
3、这个我用着vps挂着的机器人，不太清楚怎么通过网页控制。本身我连这插件本身很多开关都是很懵的，刚用起来的时候检测直播和订阅状态之类的不停在vps里刷板，也不知道开关 最后是在modules里顺着文件找到后以重命名方式关的。而项目页面的readme只有感谢 我还以为是没有教怎么使用的时候，摸索很久才发现原来里面还有个HELP.md的文件教怎么开关群功能，连带生成data文件夹。。。
4、私聊就封号好像是go-cqhttp临时会话的锅。好友间的私聊没问题（提这么个建议其实只是我个人有点需求而已）。https://github.com/Mrs4s/go-cqhttp/issues/1338

谢谢你的shebot
